const products = [
  {id:301,category:"toycode",soldOut:true,name:"Gift Card 230 Robux + ปีก Icarus",game:"ROBLOX TOY CODE",price:135,symbol:"TC",desc:"Gift Card พร้อมไอเทม Icarus สำหรับ Roblox",artA:"#34220d",artB:"#a06a20",badge:"HOT"},
  {id:302,category:"toycode",soldOut:true,name:"Hungry Orca",game:"ROBLOX TOY CODE",price:39,symbol:"TC",desc:"Toy Code ไอเทม Hungry Orca",artA:"#8e3de9",artB:"#f05de2",badge:"HOT"},
  {id:303,category:"toycode",soldOut:true,name:"Flaming Hot Chip Head",game:"ROBLOX TOY CODE",price:279,symbol:"TC",desc:"Toy Code ไอเทม Flaming Hot Chip Head",artA:"#8736e6",artB:"#ff5fcf",badge:"HOT"},
  {id:304,category:"toycode",soldOut:true,name:"Raven Hunter Hood",game:"ROBLOX TOY CODE",price:49,symbol:"TC",desc:"Toy Code ไอเทม Raven Hunter Hood",artA:"#833ee2",artB:"#d85de8",badge:"HOT"},
  {id:305,category:"toycode",soldOut:true,name:"Knife Crown",game:"ROBLOX TOY CODE",price:49,symbol:"TC",desc:"Toy Code ไอเทม Knife Crown",artA:"#7f33d5",artB:"#ca4ee6",badge:"TOY"},
  {id:306,category:"toycode",soldOut:true,name:"Doggy Backpack",game:"ROBLOX TOY CODE",price:119,symbol:"TC",desc:"Toy Code ไอเทม Doggy Backpack",artA:"#7c39dc",artB:"#e85ddb",badge:"TOY"},
  {id:307,category:"toycode",soldOut:true,name:"Freaky Fly",game:"ROBLOX TOY CODE",price:49,symbol:"TC",desc:"Toy Code ไอเทม Freaky Fly",artA:"#7231d8",artB:"#d94fdc",badge:"TOY"},
  {id:308,category:"toycode",soldOut:true,name:"Evil Clown Mask",game:"ROBLOX TOY CODE",price:189,symbol:"TC",desc:"Toy Code ไอเทม Evil Clown Mask",artA:"#6d35cf",artB:"#e251d6",badge:"TOY"},

  {id:101,category:"robux",name:"10,010 Robux แท้ (เรท 3.5)",game:"ROBLOX ROBUX",price:2860,symbol:"R$",desc:"แพ็ก Robux แท้ 10,010 Robux",artA:"#0b1b44",artB:"#3d2d8f",badge:"ลด 50%"},
  {id:102,category:"robux",name:"4,550 Robux แท้ (เรท 3.5)",game:"ROBLOX ROBUX",price:1300,symbol:"R$",desc:"แพ็ก Robux แท้ 4,550 Robux",artA:"#0b1b44",artB:"#3d2d8f",badge:"ลด 50%"},
  {id:103,category:"robux",name:"3,332 Robux แท้ (เรท 3.5)",game:"ROBLOX ROBUX",price:952,symbol:"R$",desc:"แพ็ก Robux แท้ 3,332 Robux",artA:"#0b1b44",artB:"#3d2d8f",badge:"ลด 50%"},
  {id:104,category:"robux",name:"1,820 Robux แท้ (เรท 3.5)",game:"ROBLOX ROBUX",price:520,symbol:"R$",desc:"แพ็ก Robux แท้ 1,820 Robux",artA:"#0b1b44",artB:"#3d2d8f",badge:"ลด 50%"},
  {id:105,category:"robux",name:"1,085 Robux แท้ (เรท 3.5)",game:"ROBLOX ROBUX",price:310,symbol:"R$",desc:"แพ็ก Robux แท้ 1,085 Robux",artA:"#0b1b44",artB:"#3d2d8f",badge:"ลด 50%"},
  {id:106,category:"robux",name:"840 Robux แท้ (เรท 3.5)",game:"ROBLOX ROBUX",price:240,symbol:"R$",desc:"แพ็ก Robux แท้ 840 Robux",artA:"#0b1b44",artB:"#3d2d8f",badge:"ลด 50%"},
  {id:107,category:"robux",name:"630 Robux แท้ (เรท 3.5)",game:"ROBLOX ROBUX",price:180,symbol:"R$",desc:"แพ็ก Robux แท้ 630 Robux",artA:"#0b1b44",artB:"#3d2d8f",badge:"ลด 50%"},
  {id:108,category:"robux",name:"420 Robux แท้ (เรท 3.5)",game:"ROBLOX ROBUX",price:120,symbol:"R$",desc:"แพ็ก Robux แท้ 420 Robux",artA:"#0b1b44",artB:"#3d2d8f",badge:"ลด 50%"},
  {id:109,category:"robux",name:"315 Robux แท้ (เรท 3.5)",game:"ROBLOX ROBUX",price:90,symbol:"R$",desc:"แพ็ก Robux แท้ 315 Robux",artA:"#0b1b44",artB:"#3d2d8f",badge:"ลด 50%"},
  {id:110,category:"robux",name:"210 Robux แท้ (เรท 3.5)",game:"ROBLOX ROBUX",price:60,symbol:"R$",desc:"แพ็ก Robux แท้ 210 Robux",artA:"#0b1b44",artB:"#3d2d8f",badge:"ลด 50%"},

  {id:401,category:"gamepass",comingSoon:true,name:"Steal An Egg",game:"ROBLOX GAMEPASS",price:null,symbol:"GP",desc:"Gamepass สำหรับ Steal An Egg",artA:"#0d2b62",artB:"#6337a3",badge:"GAMEPASS",selectable:true},
  {id:402,category:"gamepass",comingSoon:true,name:"+1 Speed Keyboard Escape",game:"ROBLOX GAMEPASS",price:null,symbol:"GP",desc:"Gamepass สำหรับ +1 Speed Keyboard Escape",artA:"#102f6f",artB:"#5a35a1",badge:"GAMEPASS",selectable:true},
  {id:403,category:"gamepass",comingSoon:true,name:"The Strongest Battlegrounds",game:"ROBLOX GAMEPASS",price:null,symbol:"GP",desc:"Gamepass สำหรับ The Strongest Battlegrounds",artA:"#133476",artB:"#5631a0",badge:"GAMEPASS",selectable:true},
  {id:404,category:"gamepass",comingSoon:true,name:"Rivals",game:"ROBLOX GAMEPASS",price:null,symbol:"GP",desc:"Gamepass สำหรับ Rivals",artA:"#0d2b68",artB:"#69319b",badge:"GAMEPASS",selectable:true},
  {id:405,category:"gamepass",comingSoon:true,name:"Brookhaven",game:"ROBLOX GAMEPASS",price:null,symbol:"GP",desc:"Gamepass สำหรับ Brookhaven",artA:"#12326e",artB:"#4d3498",badge:"GAMEPASS",selectable:true},
  {id:406,category:"gamepass",comingSoon:true,name:"99 Nights in the Forest",game:"ROBLOX GAMEPASS",price:null,symbol:"GP",desc:"Gamepass สำหรับ 99 Nights in the Forest",artA:"#0a2a58",artB:"#5e2e8f",badge:"GAMEPASS",selectable:true},

  {id:201,category:"farm",comingSoon:true,name:"Steal An Egg",game:"FARMING SERVICE",price:null,symbol:"FM",desc:"บริการรับฟาร์ม Steal An Egg",artA:"#111827",artB:"#211536",badge:"FARM"},
  {id:202,category:"farm",comingSoon:true,name:"Anime Expeditions",game:"FARMING SERVICE",price:null,symbol:"FM",desc:"บริการรับฟาร์ม Anime Expeditions",artA:"#111827",artB:"#211536",badge:"FARM"},
  {id:203,category:"farm",comingSoon:true,name:"Bizarre Lineage",game:"FARMING SERVICE",price:null,symbol:"FM",desc:"บริการรับฟาร์ม Bizarre Lineage",artA:"#111827",artB:"#211536",badge:"FARM"},
  {id:204,category:"farm",comingSoon:true,name:"Anime Last Stand",game:"FARMING SERVICE",price:null,symbol:"FM",desc:"บริการรับฟาร์ม Anime Last Stand",artA:"#111827",artB:"#211536",badge:"FARM"},
  {id:205,category:"farm",comingSoon:true,name:"Attack on Titan Revolution",game:"FARMING SERVICE",price:null,symbol:"FM",desc:"บริการรับฟาร์ม Attack on Titan Revolution",artA:"#111827",artB:"#211536",badge:"FARM"},
  {id:206,category:"farm",comingSoon:true,name:"Blox Fruits",game:"FARMING SERVICE",price:null,symbol:"FM",desc:"บริการรับฟาร์ม Blox Fruits",artA:"#111827",artB:"#211536",badge:"FARM"},
  {id:207,category:"farm",comingSoon:true,name:"Anime Vanguards",game:"FARMING SERVICE",price:null,symbol:"FM",desc:"บริการรับฟาร์ม Anime Vanguards",artA:"#111827",artB:"#211536",badge:"FARM"},

  {id:501,category:"farm",farmMap:"fisch",name:"ปลาลับใหม่",game:"FISCH FARMING SERVICE",price:30,symbol:"FI",desc:"บริการแมพ Fisch — ปลาลับใหม่ เซ็ตละ 30 บาท",artA:"#07111d",artB:"#14324a",badge:"FISCH",imageData:"assets/fisch-secret-fish.webp"},
  {id:502,category:"farm",farmMap:"fisch",name:"ไฮดร้า",game:"FISCH FARMING SERVICE",price:7,symbol:"FI",desc:"บริการแมพ Fisch — ไฮดร้า ตัวละ 7 บาท",artA:"#07111d",artB:"#14324a",badge:"FISCH",imageData:"assets/fisch-hydra.webp"},
  {id:503,category:"farm",farmMap:"fisch",name:"หินเอนชาจใหม่",game:"FISCH FARMING SERVICE",price:2,symbol:"FI",desc:"บริการแมพ Fisch — หินเอนชาจใหม่ อันละ 2 บาท",artA:"#07111d",artB:"#14324a",badge:"FISCH",imageData:"assets/fisch-enchant-stone.webp"},
  {id:504,category:"farm",farmMap:"fisch",name:"เนสซี",game:"FISCH FARMING SERVICE",price:7,symbol:"FI",desc:"บริการแมพ Fisch — เนสซี ตัวละ 7 บาท",artA:"#07111d",artB:"#14324a",badge:"FISCH",imageData:"assets/fisch-nessie.webp"},
  {id:505,category:"farm",farmMap:"fisch",name:"รับฟาร์มเวล 1-1000",game:"FISCH FARMING SERVICE",price:200,symbol:"FI",desc:"บริการแมพ Fisch — ฟาร์มเลเวล 1-1000",artA:"#07111d",artB:"#14324a",badge:"FISCH",imageData:"assets/fisch-level-farm.webp"},
  {id:506,category:"farm",farmMap:"fisch",name:"ฟาร์มเงินเป็นทีมใหม่ 100M",game:"FISCH FARMING SERVICE",price:220,symbol:"FI",desc:"บริการแมพ Fisch — 100M / 220 บาท",artA:"#07111d",artB:"#14324a",badge:"FISCH",imageData:"assets/fisch-money-farm.webp"}
];
